/**
 * Feature 012 T009 — generates a per-deploy compose override file that
 * names the candidate container `<service>-<color>` per research.md R-003.
 *
 * The override file is layered on top of the operator's `docker-compose.yml`
 * via `docker compose -f base.yml -f override.yml up -d`. After deploy
 * completes (success or failure), the override file is deleted.
 *
 * `generateOverride()` is a pure function (no I/O). The `writeOverride` /
 * `deleteOverride` helpers issue SSH shell-outs via the existing pool.
 */

import { sshPool } from "../services/ssh-pool.js";
import { shQuote } from "./sh-quote.js";
import { logger } from "./logger.js";

const OVERRIDE_DIR = ".dashboard"; // gitignored convention per R-003
const OVERRIDE_FILE = "docker-compose.bg-override.yml";

export type SlotColor = "blue" | "green";

/**
 * Pure function: returns YAML content for the override file. Compose
 * merges this on top of the operator's base file, naming the candidate
 * container `<service>-<slot>` deterministically.
 */
export function generateOverride(serviceName: string, slotColor: SlotColor): string {
  // NOTE: compose merges by service name; we only set container_name.
  // Indentation matters — 2-space.
  return [
    "# Generated by undev blue/green orchestrator. DO NOT EDIT MANUALLY.",
    "services:",
    `  ${serviceName}:`,
    `    container_name: ${serviceName}-${slotColor}`,
    "",
  ].join("\n");
}

export function overridePath(appDir: string): string {
  return `${appDir}/${OVERRIDE_DIR}/${OVERRIDE_FILE}`;
}

/**
 * Writes the override file to `<appDir>/.dashboard/docker-compose.bg-override.yml`
 * via SSH. Creates the directory if it does not exist. Idempotent — overwrites
 * existing file content.
 */
export async function writeOverride(
  serverId: string,
  appDir: string,
  content: string,
): Promise<void> {
  const dir = `${appDir}/${OVERRIDE_DIR}`;
  const file = overridePath(appDir);
  // mkdir -p then heredoc-write the content. shQuote on path; content is
  // delimited by an unlikely heredoc tag.
  const tag = "UNDEV_BG_OVERRIDE_EOF";
  const cmd = `mkdir -p ${shQuote(dir)} && cat > ${shQuote(file)} <<'${tag}'\n${content}\n${tag}\n`;
  try {
    const result = await sshPool.exec(serverId, cmd, 30_000);
    if (result.exitCode !== 0) {
      logger.error(
        { ctx: "compose-override-generator", serverId, appDir, code: result.exitCode, stderr: result.stderr },
        "writeOverride failed",
      );
      throw new Error(`writeOverride exited code ${result.exitCode}: ${result.stderr}`);
    }
  } catch (err) {
    logger.error(
      { ctx: "compose-override-generator", serverId, appDir, err },
      "writeOverride threw",
    );
    throw err;
  }
}

/**
 * Removes the override file. Safe to call when file does not exist
 * (uses `rm -f`).
 */
export async function deleteOverride(serverId: string, appDir: string): Promise<void> {
  const file = overridePath(appDir);
  const cmd = `rm -f ${shQuote(file)}`;
  try {
    const result = await sshPool.exec(serverId, cmd, 15_000);
    if (result.exitCode !== 0) {
      logger.warn(
        { ctx: "compose-override-generator", serverId, appDir, code: result.exitCode, stderr: result.stderr },
        "deleteOverride non-zero exit (file may already be gone)",
      );
    }
  } catch (err) {
    logger.error(
      { ctx: "compose-override-generator", serverId, appDir, err },
      "deleteOverride threw",
    );
    throw err;
  }
}
