/**
 * Phase 3 — pure generator for `docker-compose.dashboard.yml`.
 *
 * Replaces 008's admin-API push model with labels-pull. Output is a Compose
 * override file that adds `caddy: <domain>` + `caddy.reverse_proxy` labels to
 * the app's main service and joins the shared `caddy_edge` external network.
 *
 * `caddy-docker-proxy` (running on host as the reverse proxy) reads Docker
 * socket, picks up these labels, generates Caddy config, requests TLS via
 * Let's Encrypt — no dashboard intervention.
 *
 * Pure: no I/O, no logging. Caller writes the returned string to
 * `<remotePath>/docker-compose.dashboard.yml` on the target via SSH; the
 * patched `server-deploy.sh` auto-merges it via `-f`.
 */

export interface OverrideInput {
  /** Compose service name in the project's base compose file (e.g. "app", "dashboard", "9router"). */
  serviceName: string;
  /** Public hostname — must already be validated by `validateDomain`. */
  domain: string;
  /** Container port the service listens on (e.g. 3000, 8317, 20128). */
  upstreamPort: number;
  /** External Docker network name shared with caddy-docker-proxy (e.g. "ai-twins-network"). */
  edgeNetwork: string;
  /** Optional — additional `caddy.<key>: <value>` labels for middleware (auth headers, basic_auth, etc.). */
  extraLabels?: Record<string, string>;
}

// Quote when YAML semantics OR docker-compose interpolation demands it.
// `$` triggers `${VAR}` substitution in compose — always quote to avoid surprise.
const QUOTED_SCALAR_RE = /[:#&*!|>'"%@`{}\[\],$]|^[?\-]|^\s|\s$/;

function yamlScalar(v: string): string {
  // Quote only when YAML semantics demand it. Hostnames/ports never need it,
  // but middleware values (e.g. CEL expressions, path patterns) often do.
  if (v === "") return "\"\"";
  if (QUOTED_SCALAR_RE.test(v)) {
    return `"${v.replace(/\\/g, "\\\\").replace(/"/g, "\\\"")}"`;
  }
  return v;
}

export function generateCaddyOverride(input: OverrideInput): string {
  if (input.serviceName.trim() === "") throw new Error("serviceName required");
  if (input.domain.trim() === "") throw new Error("domain required");
  if (!Number.isInteger(input.upstreamPort) || input.upstreamPort < 1 || input.upstreamPort > 65535) {
    throw new Error(`invalid upstreamPort ${input.upstreamPort}`);
  }
  if (input.edgeNetwork.trim() === "") throw new Error("edgeNetwork required");

  const labelLines: string[] = [
    `      caddy: ${yamlScalar(input.domain)}`,
    `      caddy.reverse_proxy: "{{upstreams ${input.upstreamPort}}}"`,
  ];
  if (input.extraLabels) {
    for (const [k, v] of Object.entries(input.extraLabels)) {
      labelLines.push(`      ${k}: ${yamlScalar(v)}`);
    }
  }

  return [
    "# AUTO-GENERATED by devops-dashboard (Phase 3 / feature 008-revised).",
    "# DO NOT EDIT — overwritten on every deploy.",
    "# Removes when applications.domain is cleared.",
    "",
    "services:",
    `  ${input.serviceName}:`,
    `    networks:`,
    `      - default`,
    `      - caddy_edge`,
    `    labels:`,
    ...labelLines,
    "",
    "networks:",
    "  default:",
    "  caddy_edge:",
    "    external: true",
    `    name: ${yamlScalar(input.edgeNetwork)}`,
    "",
  ].join("\n");
}
